In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("Train.csv")
df

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
0,1,D,Flight,4,2,177,3,low,F,44,1233,1
1,2,F,Flight,4,5,216,2,low,M,59,3088,1
2,3,A,Flight,2,2,183,4,low,M,48,3374,1
3,4,B,Flight,3,3,176,4,medium,M,10,1177,1
4,5,C,Flight,2,2,184,3,medium,F,46,2484,1
...,...,...,...,...,...,...,...,...,...,...,...,...
10994,10995,A,Ship,4,1,252,5,medium,F,1,1538,1
10995,10996,B,Ship,4,1,232,5,medium,F,6,1247,0
10996,10997,C,Ship,5,4,242,5,low,F,4,1155,0
10997,10998,F,Ship,5,2,223,6,medium,M,2,1210,0
10998,10999,D,Ship,2,5,155,5,low,F,6,1639,0

In [11]:
df.groupby("Warehouse_block")["Customer_rating"].mean()

Warehouse_block
A    2.957447
B    2.980360
C    2.993999
D    3.017993
F    2.996727
Name: Customer_rating, dtype: float64

# SQL Queries using Pandas

### 1. Find the average cost of the product.

In [24]:
df["Cost_of_the_Product"].mean()

210.19683607600692

### 2.Find the maximum discount offered.

In [25]:
df["Discount_offered"].max()

65

### 3.Average rating by gender.

In [26]:
df.groupby('Gender')['Customer_rating'].mean()

Gender
F    2.986655
M    2.994499
Name: Customer_rating, dtype: float64

### 4.Average cost of product by warehouse

In [27]:
df.groupby('Warehouse_block')['Cost_of_the_Product'].mean()

Warehouse_block
A    208.767594
B    212.159302
C    211.191489
D    210.907852
F    209.077196
Name: Cost_of_the_Product, dtype: float64

### 5. Average rating by gender.

In [28]:
df.groupby('Gender')['Customer_rating'].mean()

Gender
F    2.986655
M    2.994499
Name: Customer_rating, dtype: float64

### 6.number of prior purchases by gender.

In [29]:
df.groupby("Gender")["Prior_purchases"].count()

Gender
F    5545
M    5454
Name: Prior_purchases, dtype: int64

### 7. heighest weight in every mode of shipment

In [33]:
df.groupby("Mode_of_Shipment")["Weight_in_gms"].max()

Mode_of_Shipment
Flight    5997
Road      6614
Ship      7846
Name: Weight_in_gms, dtype: int64

### 8.Average customer rating per Warehouse_block and Mode_of_Shipment

In [57]:
df.groupby(["Warehouse_block", "Mode_of_Shipment"])["Customer_rating"].mean()

Warehouse_block  Mode_of_Shipment
A                Flight              3.070707
                 Road                2.812925
                 Ship                2.964573
B                Flight              2.996622
                 Road                3.000000
                 Ship                2.971842
C                Flight              2.932203
                 Road                3.068027
                 Ship                2.991158
D                Flight              2.818182
                 Road                3.219178
                 Ship                3.018474
F                Flight              3.038851
                 Road                2.936860
                 Ship                3.000804
Name: Customer_rating, dtype: float64

In [58]:
df["Reached.on.Time_Y.N"].value_counts()

Reached.on.Time_Y.N
1    6563
0    4436
Name: count, dtype: int64

 ### 9. Find top 5 heaviest products.

In [62]:
df.nlargest(5,"Weight_in_gms").head(5)["ID"]

199    200
245    246
198    199
205    206
213    214
Name: ID, dtype: int64

### 10.Find the top 2 mode of shipment that delivered the highest number of on-time deliveries.

In [74]:
df[df['Reached.on.Time_Y.N'] == 1].groupby("Mode_of_Shipment")["Reached.on.Time_Y.N"].count().head(2)

Mode_of_Shipment
Flight    1069
Road      1035
Name: Reached.on.Time_Y.N, dtype: int64

### 11.For each warehouse, calculate the average number of care calls for late deliveries.

In [83]:
df[df["Reached.on.Time_Y.N"]==0].groupby("Warehouse_block")["Customer_care_calls"].mean()

Warehouse_block
A    4.171504
B    4.083676
C    4.148850
D    4.146341
F    4.167120
Name: Customer_care_calls, dtype: float64

### 12.Find the percentage of high-importance products shipped by road.

In [111]:
#d=df.groupby("Mode_of_Shipment")["Product_importance"].count().rename("count")
total_roads=df[(df["Mode_of_Shipment"]=="Road")].shape[0]
count=df[(df["Mode_of_Shipment"]=="Road") & (df["Product_importance"]=="high") ].shape[0]

print((count/total_roads)*100)

8.977272727272727

### 13.Identify the shipment mode with the lowest average weight

In [125]:
a=df.groupby("Mode_of_Shipment")["Weight_in_gms"].mean()
min(a)

3629.3781654473833

### 14.For each customer rating, find the average discount and average cost.

The .agg() method lets you apply aggregation functions (like mean, sum, count, etc.) to one or more columns.

In [ ]:
df.groupby("Customer_rating").agg({"Discount_offered":"mean","Cost_of_the_Product":"mean"})

                 Discount_offered  Cost_of_the_Product
Customer_rating
1                       13.458166           208.979866
2                       13.687760           211.387067
3                       12.979902           209.384547
4                       13.257195           210.132937
5                       13.494703           211.164901

### Count orders by product importance

In [ ]:
df.groupby("Product_importance").size()
## size() function when applied on groupby it will display the count of each group

Product_importance
high       948
low       5297
medium    4754
dtype: int64

df.size → total elements (rows × columns).

series.size → number of elements in Series.

df.groupby(...).size() → number of rows in each group.

In [ ]:
df['Product_importance'].value_counts()
# it is similar to above,but with standard function

Product_importance
low       5297
medium    4754
high       948
Name: count, dtype: int64

In [9]:
df.groupby('Mode_of_Shipment')['Customer_rating']

### Find the gender with the highest average discount received

In [16]:
a=df.groupby("Gender")["Discount_offered"].mean()
a.sort_values(ascending=False).head(1)

Gender
F    13.562489
Name: Discount_offered, dtype: float64

### Show average weight grouped by both product importance and warehouse.

That aggregation returns a Series because it has:

Index = the grouping keys (Product_importance, Warehouse_block) → this becomes a MultiIndex.

Values = the mean of Weight_in_gms.

In [23]:
a=df.groupby(['Product_importance','Warehouse_block'])['Weight_in_gms'].mean()
type(a)
a

Product_importance  Warehouse_block
high                A                  3931.103030
                    B                  3936.136986
                    C                  3939.672619
                    D                  4116.222892
                    F                  4055.435644
low                 A                  3448.829483
                    B                  3576.104094
                    C                  3492.093822
                    D                  3478.061155
                    F                  3496.861486
medium              A                  3746.376812
                    B                  3644.224760
                    C                  3742.863464
                    D                  3695.393631
                    F                  3724.073094
Name: Weight_in_gms, dtype: float64

### For each customer rating, find the percentage of on-time deliveries.

In [ ]:
df.groupby('Customer_rating')['Reached.on.Time_Y.N'].mean()*100

Customer_rating
1    58.747204
2    58.799076
3    60.607414
4    59.524897
5    60.663289
Name: Reached.on.Time_Y.N, dtype: float64